export type ScenarioCategory = 'business' | 'interview' | 'daily' | 'travel' | 'tech';

export type ScenarioObjective = {
  id: string;
  text: string;
  textTr: string;
  hint: string;
};

export type ScenarioVideoStep = {
  step: number;
  videoFile: string;
  title: string;
  aiSpeech: string;
  aiSpeechTr: string;
  expectedUserResponse: string;
  userHint: string;
  keywords: string[];
};

export type ScenarioEntry = {
  id: string;
  title: string;
  titleTr: string;
  category: ScenarioCategory;
  level: 'A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2';
  durationMin: number;
  icon: string;
  emoji: string;
  badge: string;
  description: string;
  role: string;
  aiRole: string;
  aiName: string;
  situation: string;
  objectives: ScenarioObjective[];
  starterAiMessage: string;
  suggestedVocab: { term: string; tr: string; phonetic: string }[];
  keyPhrases: { en: string; tr: string }[];
  videoPath?: string;
  videoSteps?: ScenarioVideoStep[];
  coverImage?: string;
  /** False (or absent step files) means the videoSteps data below exists but
   * the actual mp4/cover files haven't been produced yet — every screen that
   * surfaces "3D video" scenarios must gate on this, not just on
   * `videoSteps.length`, or a scenario with a written script but no footage
   * shows up as playable and the video player hangs forever on load. */
  videoReady?: boolean;
};

export const SCENARIOS: ScenarioEntry[] = [
  {
    id: 'cafe-meetup',
    title: 'Café Meetup & Ordering Coffee',
    titleTr: 'Kafede Tanışma ve Kahve Siparişi',
    category: 'daily',
    level: 'A1',
    durationMin: 6,
    icon: '☕',
    emoji: '🥐',
    badge: '3D Animasyon • Yeni',
    coverImage: 'scenarios/cafe-meetup/coffe.jpeg',
    description: 'Yankı ile kafede buluş, barista tezgahından içeceğini sipariş et ve pencere kenarında kahveni yudumlarken tanışma sohbeti yap.',
    role: 'Kafeye Gelen Arkadaş',
    aiRole: 'İngilizce Konuşma Partnerin',
    aiName: 'Yankı',
    situation: 'Yankı seni kafenin girişinde bekler, birlikte barista tezgahından sipariş verip masaya geçersiniz.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Introduce yourself with your name and country.',
        textTr: 'Adını ve ülkini söyleyerek kendini tanıt.',
        hint: 'Kalıp: "Hello Yankı! My name is... and I am from Turkey."',
      },
      {
        id: 'obj_2',
        text: 'Order a coffee or tea drink politely.',
        textTr: 'Kibarca kahve veya çay siparişi ver.',
        hint: 'Kalıp: "I would like a cappuccino, please."',
      },
      {
        id: 'obj_3',
        text: 'Share your work and why you are learning English.',
        textTr: 'Mesleğini ve neden İngilizce öğrendiğini paylaş.',
        hint: 'Kalıp: "I am working as... and I want to travel."',
      },
    ],
    starterAiMessage: "Hey! Over here! Welcome to the café! I am so happy to meet you. What is your name?",
    suggestedVocab: [
      { term: 'Cappuccino', tr: 'Kapuçino', phonetic: '/ˌkæp.əˈtʃiː.nəʊ/' },
      { term: 'Croissant', tr: 'Kruvasan', phonetic: '/ˈkwæs.ɒ̃/' },
      { term: 'Delicious', tr: 'Nefis / Lezzetli', phonetic: '/dɪˈlɪʃ.əs/' },
      { term: 'Cheers', tr: 'Şerefe / Sağlığına', phonetic: '/tʃɪəz/' },
      { term: 'Travel', tr: 'Seyahat etmek', phonetic: '/ˈtræv.əl/' },
    ],
    keyPhrases: [
      { en: 'I would like a cappuccino, please.', tr: 'Bir kapuçino rica ederim.' },
      { en: 'I am from Turkey, and I live in Istanbul.', tr: 'Türkiyeliyim ve İstanbulda yaşıyorum.' },
      { en: 'I want to travel and speak English fluently.', tr: 'Seyahat etmek ve akıcı İngilizce konuşmak istiyorum.' },
    ],
    videoPath: 'scenarios/cafe-meetup',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Girişte Karşılama',
        aiSpeech: 'Hey! Over here! Welcome to the café! I am so happy to meet you. What is your name?',
        aiSpeechTr: 'Hey! Buradayım! Kafeye hoş geldin! Seninle tanıştığıma çok sevindim. Adın neydi?',
        expectedUserResponse: 'Hello Yankı! My name is [Adın]. Nice to meet you too!',
        userHint: 'Hello Yankı! My name is... diyerek kendini tanıt.',
        keywords: ['hello', 'name', 'nice', 'meet', 'yanki', 'hi'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Barista Tezgahı & Sipariş',
        aiSpeech: "Let's get some drinks first! They have great coffee and tea here. What would you like to drink?",
        aiSpeechTr: 'Önce içeceklerimizi alalım! Burada harika kahve ve çaylar var. Ne içmek istersin?',
        expectedUserResponse: 'I would like a cappuccino, please.',
        userHint: "Sipariş ver: 'I would like a cappuccino, please' veya 'A cup of tea, please'",
        keywords: ['cappuccino', 'coffee', 'tea', 'like', 'please', 'water', 'want'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Masaya Oturma & Kahveler',
        aiSpeech: 'Mmm, this coffee smells delicious! Cheers! So, tell me, where are you from?',
        aiSpeechTr: 'Mmm, bu kahve nefis kokuyor! Şerefe! Söyle bakalım, nerelisin?',
        expectedUserResponse: 'Cheers! I am from Turkey, and I live in Istanbul.',
        userHint: "Cheers! (Şerefe) de ve 'I am from Turkey' kalıbını kullan.",
        keywords: ['cheers', 'turkey', 'from', 'live', 'istanbul', 'ankara', 'izmir'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Masada Sohbet',
        aiSpeech: 'Turkey is an amazing country! And what do you do? Are you working, or are you a student?',
        aiSpeechTr: 'Türkiye harika bir ülke! Peki ne iş yapıyorsun? Çalışıyor musun, yoksa öğrenci misin?',
        expectedUserResponse: 'I am working as an engineer.',
        userHint: 'I am working (Çalışıyorum) veya I am a student (Öğrenciyim) de.',
        keywords: ['work', 'working', 'student', 'engineer', 'job', 'study'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Neden İngilizce?',
        aiSpeech: 'That is great! So, why are you learning English? Do you want to travel to other countries?',
        aiSpeechTr: 'Çok iyi! Peki neden İngilizce öğreniyorsun? Başka ülkelere seyahat etmek istiyor musun?',
        expectedUserResponse: 'Yes, I love traveling! I want to speak English fluently.',
        userHint: 'Yes, I want to travel (Evet, seyahat etmek istiyorum) kalıbını kullan.',
        keywords: ['yes', 'travel', 'traveling', 'english', 'fluently', 'world', 'country'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Kalkış & Vedalaşma',
        aiSpeech: 'You spoke English really well today! Thank you for the coffee. Let\'s meet again tomorrow! Have a great day!',
        aiSpeechTr: 'Bugün gerçekten çok güzel İngilizce konuştun! Kahve için teşekkür ederim. Yarın yine buluşalım! Harika bir gün geçir!',
        expectedUserResponse: 'Thank you Yankı! See you tomorrow, goodbye!',
        userHint: 'Thank you Yankı! See you tomorrow, goodbye! diyerek vedalaş.',
        keywords: ['thank', 'you', 'see', 'tomorrow', 'goodbye', 'bye', 'day'],
      },
    ],
  },
  {
    id: 'airport-travel',
    title: 'Airport Check-In & Flight Departure',
    titleTr: 'Havalimanında Check-In ve Uçuş',
    category: 'travel',
    level: 'A1',
    durationMin: 6,
    icon: '✈️',
    emoji: '🧳',
    badge: '3D Animasyon • Yeni',
    coverImage: 'scenarios/airport-travel/airport.jpeg',
    description: 'Yankı ile havalimanında buluş, check-in kontuarında bilet ve pasaport işlemlerini yap, bavulunu teslim et ve uçağa biniş kapısına doğru ilerle.',
    role: 'Yolcu',
    aiRole: 'Seyahat Arkadaşın & Rehber',
    aiName: 'Yankı',
    situation: 'Yankı seni havalimanı terminalinde karşılar, check-in kontuarında bilet işlemlerini yapıp uçağa doğru beraber geçersiniz.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Check in at the desk with your ticket and documents.',
        textTr: 'Kontuarda bilet ve belgelerini göstererek check-in yap.',
        hint: 'Kalıp: "Here is my ticket and travel document."',
      },
      {
        id: 'obj_2',
        text: 'Weigh and drop off your check-in luggage.',
        textTr: 'Bavulunu tartıya koyup bagaj teslimini tamamla.',
        hint: 'Kalıp: "I have one suitcase to check in."',
      },
      {
        id: 'obj_3',
        text: 'State your seat preference (window vs. aisle).',
        textTr: 'Koltuk tercihini belirt (pencere veya koridor).',
        hint: 'Kalıp: "I prefer a window seat, please."',
      },
    ],
    starterAiMessage: 'Welcome to the airport! We have a flight to catch. Are you ready for check-in?',
    suggestedVocab: [
      { term: 'Boarding Pass', tr: 'Biniş kartı', phonetic: '/ˈbɔː.dɪŋ ˌpɑːs/' },
      { term: 'Suitcase', tr: 'Bavul / Valiz', phonetic: '/ˈsuːt.keɪs/' },
      { term: 'Luggage', tr: 'Bagaj', phonetic: '/ˈlʌɡ.ɪdʒ/' },
      { term: 'Gate', tr: 'Uçuş kapısı', phonetic: '/ɡeɪt/' },
      { term: 'Window Seat', tr: 'Pencere kenarı koltuk', phonetic: '/ˈwɪn.dəʊ siːt/' },
      { term: 'Aisle Seat', tr: 'Koridor koltuğu', phonetic: '/aɪl siːt/' },
    ],
    keyPhrases: [
      { en: 'Here is my ticket and travel document.', tr: 'İşte biletim ve seyahat belgem.' },
      { en: 'I have one suitcase to check in.', tr: 'Teslim edilecek bir bavulum var.' },
      { en: 'I prefer a window seat so I can see outside.', tr: 'Dışarıyı görebilmek için pencere kenarını tercih ederim.' },
      { en: 'Have a safe flight and wonderful journey!', tr: 'İyi uçuşlar ve harika bir yolculuk dilerim!' },
    ],
    videoPath: 'scenarios/airport-travel',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Havalimanına Varış & Bilgi Ekranı',
        aiSpeech: 'Welcome to the airport! We have a flight to catch. Are you ready for check-in?',
        aiSpeechTr: 'Havalimanına hoş geldin! Yetişmemiz gereken bir uçuş var. Check-in için hazır mısın?',
        expectedUserResponse: 'Yes, I am ready! Which airline are we flying with?',
        userHint: 'Yes, I am ready! (Evet hazırım) diyerek başla.',
        keywords: ['yes', 'ready', 'flight', 'check-in', 'airline', 'airport'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Check-In Deski & Belgeler',
        aiSpeech: 'First, let\'s check in! Do you have your ticket and travel documents with you?',
        aiSpeechTr: 'Önce check-in yapalım! Biletin ve seyahat belgelerin yanında mı?',
        expectedUserResponse: 'Yes, here is my ticket and travel document.',
        userHint: 'Here is my ticket (İşte biletim) kalıbını kullan.',
        keywords: ['here', 'ticket', 'travel', 'document', 'passport', 'yes'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Bagaj Tartımı & Bavul Teslimi',
        aiSpeech: 'Please put your suitcase on the luggage scale. How many bags are you checking in today?',
        aiSpeechTr: 'Lütfen bavulunu bagaj tartısına koy. Bugün kaç parça valiz veriyorsun?',
        expectedUserResponse: 'I have one suitcase to check in, and this small backpack as carry-on.',
        userHint: 'I have one suitcase (Bir bavulum var) diyerek yanıtla.',
        keywords: ['one', 'suitcase', 'bag', 'backpack', 'carry-on', 'check'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Güvenlik Kontrolü & X-Ray Tepsisi',
        aiSpeech: 'We need to pass through security screening now. Please place your electronics in the plastic tray.',
        aiSpeechTr: 'Şimdi güvenlik kontrolünden geçmemiz gerekiyor. Lütfen elektronik cihazlarını plastik tepsiye koy.',
        expectedUserResponse: 'Sure, here is my laptop and phone in the tray.',
        userHint: 'Sure, here is my laptop (Elbette, işte dizüstü bilgisayarım) de.',
        keywords: ['sure', 'laptop', 'phone', 'tray', 'electronics', 'here'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Kapı Bekleme Alanı & Koltuk Tercihi',
        aiSpeech: 'Our flight departs from Gate 14. Which seat do you prefer: window seat or aisle seat?',
        aiSpeechTr: 'Uçağımız 14 numaralı kapıdan kalkıyor. Hangi koltuğu tercih edersin: pencere kenarı mı, koridor mu?',
        expectedUserResponse: 'I prefer a window seat so I can see the clouds.',
        userHint: 'I prefer a window seat (Pencere kenarını tercih ederim) de.',
        keywords: ['window', 'aisle', 'seat', 'prefer', 'clouds', 'like'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Uçağa Biniş & İyi Uçuşlar',
        aiSpeech: 'Our flight is boarding now! You spoke great English at the airport. Have a wonderful flight and safe travels!',
        aiSpeechTr: 'Uçağımız binişe başladı! Havalimanında harika İngilizce konuştun. Harika bir uçuş ve güvenli yolculuklar dilerim!',
        expectedUserResponse: 'Thank you so much Yankı! Have a great journey too, goodbye!',
        userHint: 'Thank you Yankı! Have a great journey (Sana da iyi yolculuklar) diyerek vedalaş.',
        keywords: ['thank', 'you', 'flight', 'safe', 'journey', 'goodbye', 'bye'],
      },
    ],
  },
  {
    id: 'neighbor-meetup',
    title: 'Meeting the New Neighbor & Welcome Chat',
    titleTr: 'Yeni Komşu ile Tanışma & Hoş Geldin Sohbeti',
    category: 'daily',
    level: 'A1',
    durationMin: 6,
    icon: '🏡',
    emoji: '🪴',
    badge: '3D Animasyon • Yeni',
    coverImage: 'scenarios/neighbor-meetup/neighbor.jpeg',
    description: 'Yeni taşındığın binada komşun Yankı ile koridorda karşılaş, tanışma sohbeti yap, mahalle önerilerini dinle ve hafta sonu çay davetini kabul et.',
    role: 'Yeni Taşınan Komşu',
    aiRole: 'Yan Dairedeki Komşun',
    aiName: 'Yankı',
    situation: 'Yankı koridorda senin yeni taşındığını görür, elinde hoş geldin hediyesiyle yanına gelerek sıcak bir tanışma başlatır.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Introduce yourself and confirm you moved in today.',
        textTr: 'Kendini tanıt ve bugün taşındığını belirt.',
        hint: 'Kalıp: "Hello! Yes, I just moved in today."',
      },
      {
        id: 'obj_2',
        text: 'State your apartment and floor number.',
        textTr: 'Daire ve kat numaranı paylaş.',
        hint: 'Kalıp: "I live on the second floor, in apartment 7."',
      },
      {
        id: 'obj_3',
        text: 'Ask for directions to the nearest supermarket or bakery.',
        textTr: 'En yakın market veya fırının yerini sor.',
        hint: 'Kalıp: "Where is the nearest supermarket?"',
      },
    ],
    starterAiMessage: 'Hello there! Welcome to the building! Did you just move in today?',
    suggestedVocab: [
      { term: 'Neighbor', tr: 'Komşu', phonetic: '/ˈneɪ.bər/' },
      { term: 'Building', tr: 'Bina / Apartman', phonetic: '/ˈbɪl.dɪŋ/' },
      { term: 'Apartment', tr: 'Daire', phonetic: '/əˈpɑːt.mənt/' },
      { term: 'Bakery', tr: 'Fırın / Pastane', phonetic: '/ˈbeɪ.kər.i/' },
      { term: 'Supermarket', tr: 'Süpermarket', phonetic: '/ˈsuː.pəˌmɑː.kɪt/' },
      { term: 'Unpack', tr: 'Kutuları açmak / Yerleşmek', phonetic: '/ʌnˈpæk/' },
    ],
    keyPhrases: [
      { en: 'Nice to meet you, I just moved in today.', tr: 'Tanıştığımıza memnun oldum, bugün taşındım.' },
      { en: 'I live on the second floor in apartment seven.', tr: 'İkinci katta yedi numaralı dairede oturuyorum.' },
      { en: 'Where is the nearest supermarket around here?', tr: 'Buralardaki en yakın süpermarket nerede?' },
      { en: 'Thank you for being so welcoming!', tr: 'Bu kadar sıcak karşıladığınız için teşekkür ederim!' },
    ],
    videoPath: 'scenarios/neighbor-meetup',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Koridorda Karşılaşma & Hoş Geldin',
        aiSpeech: 'Hello there! Welcome to the building! Did you just move in today?',
        aiSpeechTr: 'Merhaba! Binaya hoş geldin! Buraya bugün mü taşındın?',
        expectedUserResponse: 'Hello! Yes, I just moved in today. Nice to meet you!',
        userHint: 'Hello! Yes, I just moved in today (Evet bugün taşındım) diyerek kendini tanıt.',
        keywords: ['hello', 'yes', 'moved', 'today', 'nice', 'meet', 'neighbor'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'İsim Tanışması & Daire Numarası',
        aiSpeech: 'I am Yanki, and I live in apartment number 4. Which floor are you on?',
        aiSpeechTr: 'Ben Yankı, 4 numaralı dairede oturuyorum. Sen kaçıncı kattasın?',
        expectedUserResponse: 'Nice to meet you Yanki! I live on the second floor, in apartment 7.',
        userHint: 'I live on the second floor (İkinci katta oturuyorum) kalıbını kullan.',
        keywords: ['nice', 'yanki', 'live', 'floor', 'apartment', 'second', 'first'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Taşınma Kutuları & Yardım Teklifi',
        aiSpeech: 'Moving into a new home can be tiring! Do you need any help with your boxes?',
        aiSpeechTr: 'Yeni bir eve taşınmak yorucu olabilir! Kutuların için yardıma ihtiyacın var mı?',
        expectedUserResponse: 'Thank you so much, but I am almost finished unpacking!',
        userHint: 'Thank you so much, but I am almost finished (Neredeyse bitirdim) diyerek teşekkür et.',
        keywords: ['thank', 'you', 'help', 'almost', 'finished', 'fine', 'boxes'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Mahalle Rehberi & Süpermarket',
        aiSpeech: 'There is a fresh bakery and a great supermarket right around the corner. Would you like directions?',
        aiSpeechTr: 'Köşeyi dönünce taze bir fırın ve harika bir süpermarket var. Yol tarifini ister misin?',
        expectedUserResponse: 'That would be wonderful! Where is the nearest supermarket?',
        userHint: 'That would be wonderful (Çok iyi olur) diyerek süpermarketin yerini sor.',
        keywords: ['wonderful', 'where', 'nearest', 'supermarket', 'bakery', 'thanks', 'yes'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Sessiz Saatler & Komşuluk Desteği',
        aiSpeech: 'Our apartment building is very quiet and friendly. If you ever need anything, just knock on my door!',
        aiSpeechTr: 'Apartmanımız çok sessiz ve samimidir. Bir şeye ihtiyacın olursa kapımı çalman yeterli!',
        expectedUserResponse: 'That is very kind of you! Thank you for being so welcoming.',
        userHint: 'That is very kind of you (Çok naziksiniz) kalıbıyla karşılık ver.',
        keywords: ['kind', 'thank', 'you', 'welcoming', 'door', 'good', 'neighbor'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Hafta Sonu Çay Daveti & Vedalaşma',
        aiSpeech: 'Good luck with unpacking! Let us have some tea together this weekend. Have a wonderful day!',
        aiSpeechTr: 'Kutuları açarken kolay gelsin! Bu hafta sonu birlikte çay içelim. Harika bir gün geçir!',
        expectedUserResponse: 'Sounds great! See you this weekend, goodbye Yanki!',
        userHint: 'Sounds great! See you this weekend (Kulağa harika geliyor, hafta sonu görüşürüz) de.',
        keywords: ['sounds', 'great', 'see', 'weekend', 'tea', 'goodbye', 'bye'],
      },
    ],
  },
  {
    id: 'hotel-checkin',
    title: 'Hotel Check-In & Room Preferences',
    titleTr: 'Otelde Check-In & Oda Tercihleri',
    category: 'travel',
    level: 'A1',
    durationMin: 6,
    icon: '🛎️',
    emoji: '🏨',
    badge: '3D Animasyon • Yeni Karakter',
    coverImage: 'scenarios/hotel-checkin/hotel.jpeg',
    description: 'Grand Hotel lobisinde resepsiyonist Oliver ile tanış, rezervasyonunu teyit et, oda tercihini belirt, Wi-Fi ve kahvaltı bilgilerini alıp oda kartını teslim al.',
    role: 'Otel Misafiri',
    aiRole: 'Otel Resepsiyonisti',
    aiName: 'Oliver',
    situation: 'Oliver seni Grand Hotel resepsiyon tezgahında karşılar, rezervasyon işlemlerini tamamlayıp oda anahtarını teslim eder.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Confirm your reservation at the front desk.',
        textTr: 'Resepsiyonda rezervasyonunu teyit et.',
        hint: 'Kalıp: "Yes, I have a reservation under my name."',
      },
      {
        id: 'obj_2',
        text: 'State your room preference (higher floor or garden view).',
        textTr: 'Oda tercihini belirt (yüksek kat veya bahçe manzarası).',
        hint: 'Kalıp: "I would prefer a room on a higher floor, please."',
      },
      {
        id: 'obj_3',
        text: 'Ask about breakfast times and location.',
        textTr: 'Kahvaltı saatini ve salonun yerini sor.',
        hint: 'Kalıp: "Where is the breakfast room located?"',
      },
    ],
    starterAiMessage: 'Good afternoon! Welcome to the Grand Hotel. Do you have a reservation with us?',
    suggestedVocab: [
      { term: 'Reservation', tr: 'Rezervasyon', phonetic: '/ˌrez.əˈveɪ.ʃən/' },
      { term: 'Keycard', tr: 'Elektronik kart anahtar', phonetic: '/ˈkiː.kɑːd/' },
      { term: 'Elevator', tr: 'Asansör', phonetic: '/ˈel.ɪ.veɪ.tər/' },
      { term: 'Reception', tr: 'Resepsiyon / Danışma', phonetic: '/rɪˈsep.ʃən/' },
      { term: 'Luggage', tr: 'Bagaj / Bavul', phonetic: '/ˈlʌɡ.ɪdʒ/' },
      { term: 'Higher Floor', tr: 'Yüksek kat', phonetic: '/ˈhaɪ.ər flɔːr/' },
    ],
    keyPhrases: [
      { en: 'Yes, I have a reservation under my name.', tr: 'Evet, adıma yapılmış bir rezervasyonum var.' },
      { en: 'Here is my booking confirmation and travel document.', tr: 'İşte rezervasyon onayım ve seyahat belgem.' },
      { en: 'I would prefer a room with a nice view.', tr: 'Güzel manzaralı bir oda tercih ederim.' },
      { en: 'We hope you enjoy your stay with us!', tr: 'Umarız bizimle harika bir konaklama geçirirsiniz!' },
    ],
    videoPath: 'scenarios/hotel-checkin',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Resepsiyonda Karşılama & Rezervasyon',
        aiSpeech: 'Good afternoon! Welcome to the Grand Hotel. Do you have a reservation with us?',
        aiSpeechTr: 'Tünaydın! Grand Hotel\'e hoş geldiniz. Bizde bir rezervasyonunuz var mıydı?',
        expectedUserResponse: 'Good afternoon! Yes, I have a reservation under my name.',
        userHint: 'Good afternoon! Yes, I have a reservation (Evet rezervasyonum var) diyerek başla.',
        keywords: ['good', 'afternoon', 'reservation', 'name', 'yes', 'hotel', 'hello'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Rezervasyon Onayı & Belgeler',
        aiSpeech: 'Perfect! May I please see your booking confirmation and travel documents?',
        aiSpeechTr: 'Harika! Check-in işlemini tamamlamak için rezervasyon onayınızı ve seyahat belgelerinizi görebilir miyim?',
        expectedUserResponse: 'Sure, here is my booking confirmation and travel document.',
        userHint: 'Sure, here is my booking confirmation (Elbette, işte rezervasyon onayım) kalıbını kullan.',
        keywords: ['sure', 'here', 'booking', 'confirmation', 'travel', 'document', 'please', 'yes'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Oda Tercihi & Kat Seçimi',
        aiSpeech: 'Thank you. Would you prefer a room on a higher floor or closer to the garden?',
        aiSpeechTr: 'Teşekkürler. Yüksek katta bir oda mı yoksa bahçeye yakın bir oda mı tercih edersiniz?',
        expectedUserResponse: 'I would prefer a room on a higher floor with a nice view, please.',
        userHint: 'I would prefer a room on a higher floor (Yüksek katta bir oda tercih ederim) de.',
        keywords: ['prefer', 'higher', 'floor', 'view', 'garden', 'room', 'please'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Kahvaltı & Wi-Fi Bilgileri',
        aiSpeech: 'Breakfast is served every morning from seven to ten, and Wi-Fi is completely free.',
        aiSpeechTr: 'Kahvaltı her sabah yedi ile on arasında servis edilir ve Wi-Fi tamamen ücretsizdir.',
        expectedUserResponse: 'That sounds great! Where is the breakfast room located?',
        userHint: 'That sounds great! Where is breakfast? (Kahvaltı nerede?) diyerek sor.',
        keywords: ['sounds', 'great', 'where', 'breakfast', 'located', 'room', 'thank'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Oda Kartı & Asansör Yönlendirmesi',
        aiSpeech: 'Here is your electronic room keycard for room 305. The elevators are just to your right.',
        aiSpeechTr: 'İşte 305 numaralı odanız için elektronik kart anahtarınız. Asansörler hemen sağınızda.',
        expectedUserResponse: 'Thank you very much! Does this keycard also open the main entrance?',
        userHint: 'Thank you very much! (Çok teşekkür ederim) diyerek anahtar kartını al.',
        keywords: ['thank', 'much', 'keycard', 'open', 'door', 'room', 'elevator'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Bagaj Yardımı & İyi Konaklamalar',
        aiSpeech: 'Our bellboy can help with your luggage. We hope you enjoy your stay with us!',
        aiSpeechTr: 'Belboyumuz bagajlarınız için yardımcı olabilir. Umarız bizimle harika bir konaklama geçirirsiniz!',
        expectedUserResponse: 'Thank you for your help, Oliver! Have a wonderful day, goodbye!',
        userHint: 'Thank you for your help! (Yardımın için teşekkürler) diyerek iyi günler dile.',
        keywords: ['thank', 'help', 'oliver', 'wonderful', 'day', 'goodbye', 'bye'],
      },
    ],
  },
  {
    id: 'taxi-ride',
    title: 'London Taxi Ride & Sightseeing',
    titleTr: 'Londra Taksi Yolculuğu & Şehir Rehberi',
    category: 'travel',
    level: 'A2',
    durationMin: 7,
    icon: '🚕',
    emoji: '🇬🇧',
    badge: '3D Animasyon • Yeni Karakter',
    coverImage: 'scenarios/taxi-ride/taxi.jpeg',
    description: 'Londra\'da ikonik siyah taksiye bin, sıcakkanlı taksici Sam ile nereye gideceğini konuş, rota ve trafik hakkında bilgi al, Big Ben manzarasını izle ve ücreti öde.',
    role: 'Yolcu',
    aiRole: 'Londra Taksi Şoförü',
    aiName: 'Sam',
    situation: 'Sam seni Londra\'nın yağmurlu bir gününde ikonik siyah taksisinde karşılar, müzeye doğru yola çıkarken şehir hakkında rehberlik eder.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Tell the driver your destination clearly.',
        textTr: 'Şoföre varış noktanızı net olarak belirtin.',
        hint: 'Kalıp: "Could you please take me to the British Museum?"',
      },
      {
        id: 'obj_2',
        text: 'Ask how long the journey will take.',
        textTr: 'Yolculuğun ne kadar süreceğini sorun.',
        hint: 'Kalıp: "How long will the ride take?"',
      },
      {
        id: 'obj_3',
        text: 'Pay the fare by contactless card and leave a tip.',
        textTr: 'Ücreti temassız kartla ödeyip bahşiş bırakın.',
        hint: 'Kalıp: "Here is my card, keep the change."',
      },
    ],
    starterAiMessage: 'Hello there! Jump right in and make yourself comfortable. Where can I take you today?',
    suggestedVocab: [
      { term: 'Fare', tr: 'Taksi / Bilet ücreti', phonetic: '/feər/' },
      { term: 'Destination', tr: 'Varış noktası / Hedef', phonetic: '/ˌdes.tɪˈneɪ.ʃən/' },
      { term: 'Scenic route', tr: 'Manzaralı rota', phonetic: '/ˈsiː.nɪk ruːt/' },
      { term: 'Contactless', tr: 'Temassız (ödeme)', phonetic: '/ˈkɒn.tækt.ləs/' },
      { term: 'Tip', tr: 'Bahşiş', phonetic: '/tɪp/' },
      { term: 'Keep the change', tr: 'Üstü kalsın', phonetic: '/kiːp ðə tʃeɪndʒ/' },
    ],
    keyPhrases: [
      { en: 'Could you please take me to the British Museum?', tr: 'Beni British Museum\'a götürebilir misiniz?' },
      { en: 'How long will the ride take?', tr: 'Yolculuk ne kadar sürer?' },
      { en: 'Look out your left window, you can see Big Ben!', tr: 'Sol pencerenizden dışarı bakın, Big Ben\'i görebilirsiniz!' },
      { en: 'Here is my card, keep the change as a tip!', tr: 'İşte kartım, üstü bahşiş olarak kalsın!' },
    ],
    videoPath: 'scenarios/taxi-ride',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Taksiye Biniş & Varış Noktası',
        aiSpeech: 'Hello there! Jump right in and make yourself comfortable. Where can I take you today?',
        aiSpeechTr: 'Merhaba! Hemen atlayın ve rahatınıza bakın. Sizi bugün nereye götürebilirim?',
        expectedUserResponse: 'Hello! Could you please take me to the British Museum?',
        userHint: 'Hello! Could you take me to the British Museum? (Beni British Museum\'a götürebilir misiniz?) de.',
        keywords: ['hello', 'take', 'british', 'museum', 'please', 'could', 'to'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Rota Tercihi & Trafik Durumu',
        aiSpeech: 'The British Museum, brilliant! Traffic is a bit busy on Oxford Street, so I will take the scenic river route.',
        aiSpeechTr: 'British Museum, harika! Oxford Caddesi\'nde trafik biraz yoğun, bu yüzden nehir kenarındaki manzaralı rotadan gideceğim.',
        expectedUserResponse: 'That sounds wonderful! How long will the ride take?',
        userHint: 'That sounds wonderful! How long will it take? (Yolculuk ne kadar sürer?) diyerek sor.',
        keywords: ['sounds', 'wonderful', 'great', 'how', 'long', 'take', 'ride', 'time'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Şehir Simgeleri & Big Ben Manzarası',
        aiSpeech: 'It should take about fifteen minutes. Look out your left window, you can see Big Ben and the river Thames!',
        aiSpeechTr: 'Yaklaşık on beş dakika sürer. Sol pencerenizden dışarı bakın, Big Ben ve Thames nehrini görebilirsiniz!',
        expectedUserResponse: 'Wow, the view is spectacular! London looks so beautiful in this weather.',
        userHint: 'The view is spectacular! (Manzara muhteşem!) diyerek heyecanını paylaş.',
        keywords: ['view', 'spectacular', 'beautiful', 'london', 'wow', 'amazing', 'weather'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Müze Tavsiyesi & Bilet Bilgisi',
        aiSpeech: 'Are you visiting London for holiday? The museum has free entry, but remember to book an online timed ticket!',
        aiSpeechTr: 'Londra\'yı tatil için mi ziyaret ediyorsunuz? Müzeye giriş ücretsizdir ama internetten saatli bilet almayı unutmayın!',
        expectedUserResponse: 'Yes, I am on vacation! Thank you for the advice, I already reserved my ticket.',
        userHint: 'Yes, I am on vacation! (Evet, tatildeyim!) de ve tavsiyesi için teşekkür et.',
        keywords: ['yes', 'vacation', 'holiday', 'thank', 'advice', 'reserved', 'ticket', 'already'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Müzeye Varış & Taksi Ücreti',
        aiSpeech: 'And here we are, right outside the main museum gates! The total fare is fourteen pounds, card or cash is fine.',
        aiSpeechTr: 'Ve işte geldik, tam ana müze kapısının önündeyiz! Toplam ücret 14 pound, kart veya nakit kabul edebilirim.',
        expectedUserResponse: 'Here is my contactless card. Keep the change as a tip, thank you!',
        userHint: 'Here is my contactless card (İşte temassız kartım) de ve bahşiş bırak.',
        keywords: ['here', 'card', 'contactless', 'change', 'tip', 'thank', 'fourteen', 'pounds'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Ödeme Onayı & İyi Günler Dileği',
        aiSpeech: 'Payment went through smoothly! Mind your step getting out, and enjoy your time in London!',
        aiSpeechTr: 'Ödeme sorunsuzca geçti! İnerken basamağa dikkat edin ve Londra\'daki vaktinizin tadını çıkarın!',
        expectedUserResponse: 'Thank you so much for the lovely ride, Sam! Have a great day, goodbye!',
        userHint: 'Thank you so much for the lovely ride! (Güzel yolculuk için çok teşekkürler!) diyerek vedalaş.',
        keywords: ['thank', 'lovely', 'ride', 'sam', 'great', 'day', 'goodbye', 'bye'],
      },
    ],
  },
  {
    id: 'restaurant-dinner',
    title: 'Italian Dinner & Ordering Food',
    titleTr: 'İtalyan Restoranında Akşam Yemeği',
    category: 'daily',
    level: 'A2',
    durationMin: 7,
    icon: '🍝',
    emoji: '🍷',
    badge: '3D Animasyon • Yeni',
    coverImage: 'scenarios/restaurant-dinner/restaurant.jpeg',
    description: 'Trattoria Bella\'da masaya geç, sıcakkanlı İtalyan şef Marco ile tanış, günün deniz ürünlü fettuccine spesiyalını sipariş et, tiramisu ve espresso ile harika bir akşam geçir.',
    role: 'Restorana Gelen Misafir',
    aiRole: 'İtalyan Şef & Garson',
    aiName: 'Marco',
    situation: 'Marco seni Trattoria Bella girişinde sıcak bir gülümsemeyle karşılar, menüyü takdim eder ve günün özel makarnasını önerir.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Request a table politely for your dinner.',
        textTr: 'Akşam yemeği için kibarca bir masa talep et.',
        hint: 'Kalıp: "Good evening! A table for one by the window, please."',
      },
      {
        id: 'obj_2',
        text: 'Order a drink and the chef\'s special fettuccine.',
        textTr: 'Bir içecek ve şefin tavsiye ettiği fettuccineyi sipariş et.',
        hint: 'Kalıp: "The fettuccine sounds delicious! I will have that, please."',
      },
      {
        id: 'obj_3',
        text: 'Give feedback about the food and order dessert.',
        textTr: 'Yemek hakkında olumlu geri bildirim ver ve tiramisu siparişi ver.',
        hint: 'Kalıp: "Everything is delicious! I cannot resist tiramisu, please."',
      },
    ],
    starterAiMessage: 'Good evening! Welcome to Trattoria Bella. Table for one or two tonight?',
    suggestedVocab: [
      { term: 'Fettuccine', tr: 'Fettuccine makarnası', phonetic: '/ˌfet.əˈtʃiː.ni/' },
      { term: 'Sparkling water', tr: 'Maden suyu / Gazlı su', phonetic: '/ˈspɑː.klɪŋ ˈwɔː.tər/' },
      { term: 'Chef special', tr: 'Günün şef spesiyali', phonetic: '/ʃef ˈspeʃ.əl/' },
      { term: 'Delicious', tr: 'Lezzetli / Nefis', phonetic: '/dɪˈlɪʃ.əs/' },
      { term: 'Tiramisu', tr: 'Tiramisu tatlısı', phonetic: '/ˌtɪr.ə.mɪˈsuː/' },
      { term: 'Bill', tr: 'Hesap / Adisyon', phonetic: '/bɪl/' },
    ],
    keyPhrases: [
      { en: 'Good evening! A table for one, please.', tr: 'İyi akşamlar! Tek kişilik bir masa lütfen.' },
      { en: 'I would like a glass of sparkling water with lemon.', tr: 'Limonlu bir bardak maden suyu rica ederim.' },
      { en: 'The fettuccine sounds delicious! I will have that.', tr: 'Fettuccine kulağa harika geliyor! Ondan alayım.' },
      { en: 'Everything is absolutely delicious, thank you!', tr: 'Her şey son derece lezzetli, teşekkürler!' },
      { en: 'Can I pay with card? Keep the change as a tip!', tr: 'Kartla ödeyebilir miyim? Üstü bahşiş olarak kalsın!' },
    ],
    videoPath: 'scenarios/restaurant-dinner',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Masaya Karşılama & Menü Takdimi',
        aiSpeech: 'Good evening! Welcome to Trattoria Bella. Table for one or two tonight?',
        aiSpeechTr: 'İyi akşamlar! Trattoria Bella\'ya hoş geldiniz. Bu akşam bir mi iki kişilik masa mı arzu edersiniz?',
        expectedUserResponse: 'Good evening! A table for one by the window, please.',
        userHint: 'Good evening! A table for one, please (Tek kişilik bir masa lütfen) diyerek başla.',
        keywords: ['good', 'evening', 'table', 'one', 'two', 'window', 'please'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Başlangıç & İçecek Siparişi',
        aiSpeech: 'Right this way! Can I start you off with some sparkling water or wine?',
        aiSpeechTr: 'Bu taraftan lütfen! Başlangıç olarak maden suyu veya şarap ikram edebilir miyim?',
        expectedUserResponse: 'I would like a glass of sparkling water with lemon, please.',
        userHint: 'I would like a glass of sparkling water (Bir bardak maden suyu lütfen) kalıbını kullan.',
        keywords: ['would', 'like', 'glass', 'water', 'sparkling', 'lemon', 'wine', 'please'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Günün Spesiyali & Ana Yemek Siparişi',
        aiSpeech: 'Our chef\'s special tonight is handmade seafood fettuccine. What would you like for dinner?',
        aiSpeechTr: 'Şefimizin bu akşamki spesiyali el yapımı deniz ürünlü fettuccine. Akşam yemeği için ne arzu edersiniz?',
        expectedUserResponse: 'The fettuccine sounds delicious! I will have that, please.',
        userHint: 'The fettuccine sounds delicious! I will have that (Ondan alayım lütfen) de.',
        keywords: ['fettuccine', 'sounds', 'delicious', 'will', 'have', 'that', 'please', 'pasta'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Yemek Kontrolü & Lezzet Geri Bildirimi',
        aiSpeech: 'How is everything tasting tonight? Is the pasta cooked to your liking?',
        aiSpeechTr: 'Yemeğinizin tadı nasıl, her şey yolunda mı? Makarnanız tam istediğiniz kıvamda mı?',
        expectedUserResponse: 'Everything is absolutely delicious! The pasta is perfect, thank you.',
        userHint: 'Everything is absolutely delicious! (Her şey son derece lezzetli!) diyerek teşekkür et.',
        keywords: ['everything', 'delicious', 'pasta', 'perfect', 'thank', 'tasting', 'good'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Tatlı & Espresso Önerisi',
        aiSpeech: 'Wonderful! Room for dessert? We have fresh homemade tiramisu and hot espresso.',
        aiSpeechTr: 'Harika! Tatlıya yeriniz var mı? Taze ev yapımı tiramisu ve sıcak espressomuz var.',
        expectedUserResponse: 'I cannot resist tiramisu! One tiramisu and an espresso, please.',
        userHint: 'One tiramisu and an espresso, please (Bir tiramisu ve bir espresso lütfen) diyerek sipariş ver.',
        keywords: ['tiramisu', 'espresso', 'one', 'please', 'dessert', 'resist', 'coffee'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Hesap & Bahşiş Bırakma',
        aiSpeech: 'Here is your bill! Take your time, whenever you are ready.',
        aiSpeechTr: 'İşte hesabınız! Acele etmeyin, ne zaman hazır olursanız buradayım.',
        expectedUserResponse: 'Can I pay with card? Keep the change as a tip, thank you so much!',
        userHint: 'Can I pay with card? (Kartla ödeyebilir miyim?) de ve bahşiş bırak.',
        keywords: ['bill', 'pay', 'card', 'keep', 'change', 'tip', 'thank', 'much'],
      },
    ],
  },
  {
    id: 'doctor-visit',
    title: "Doctor's Consultation & Health Check",
    titleTr: 'Doktor Muayenesi & Sağlık Şikayeti',
    category: 'daily',
    level: 'A2',
    durationMin: 8,
    icon: '🩺',
    emoji: '💊',
    badge: '3D Animasyon • Yeni',
    coverImage: 'scenarios/doctor-visit/doctor.jpeg',
    description: 'Londra kliniğinde Dr. Emma ile görüş, baş ve boğaz ağrısı şikayetlerini anlat, muayeneden geç, reçeteni al ve sağlığına hızla kavuş.',
    role: 'Kliniğe Gelen Hasta',
    aiRole: 'Aile Hekimi & Doktor',
    aiName: 'Dr. Emma',
    situation: 'Dr. Emma seni aydınlık muayene odasında güler yüzle karşılar, oturmanı ister ve şikayetlerini dinleyip muayene eder.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Explain your symptoms (headache and sore throat) clearly.',
        textTr: 'Şikayetlerini (baş ve boğaz ağrısı) açıkça ifade et.',
        hint: 'Kalıp: "I have had a terrible headache and a sore throat since yesterday."',
      },
      {
        id: 'obj_2',
        text: 'Describe your fever and answer examination questions.',
        textTr: 'Ateş durumunu tarif et ve muayene komutlarını uygula.',
        hint: 'Kalıp: "Yes, I felt feverish last night, my temperature was around 38 degrees."',
      },
      {
        id: 'obj_3',
        text: 'Ask about medication and thank the doctor for the advice.',
        textTr: 'İlaç kullanımı hakkında soru sor ve doktora teşekkür et.',
        hint: 'Kalıp: "How often should I use the spray? Thank you for your care, Dr. Emma!"',
      },
    ],
    starterAiMessage: 'Good morning! Please take a seat. What brings you into the clinic today?',
    suggestedVocab: [
      { term: 'Headache', tr: 'Baş ağrısı', phonetic: '/ˈhed.eɪk/' },
      { term: 'Sore throat', tr: 'Boğaz ağrısı', phonetic: '/sɔːr θrəʊt/' },
      { term: 'Fever', tr: 'Ateş', phonetic: '/ˈfiː.vər/' },
      { term: 'Inflamed', tr: 'İltihaplı / Kızarmış', phonetic: '/ɪnˈfleɪmd/' },
      { term: 'Prescription', tr: 'Reçete', phonetic: '/prɪˈskrɪp.ʃən/' },
      { term: 'Fluids', tr: 'Sıvılar', phonetic: '/ˈfluː.ɪdz/' },
    ],
    keyPhrases: [
      { en: 'I have had a terrible headache and a sore throat.', tr: 'Dünden beri şiddetli baş ve boğaz ağrım var.' },
      { en: 'My temperature was around 38 degrees.', tr: 'Ateşim 38 derece civarındaydı.' },
      { en: 'Do I need to take any antibiotics for this?', tr: 'Bunun için antibiyotik almam gerekiyor mu?' },
      { en: 'How often should I use the throat spray?', tr: 'Boğaz spreyini ne sıklıkla kullanmalıyım?' },
      { en: 'Thank you so much for your care, doctor!', tr: 'İlginiz için çok teşekkürler doktor!' },
    ],
    videoPath: 'scenarios/doctor-visit',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Klinikte Karşılama & Şikayeti Anlatma',
        aiSpeech: 'Good morning! Please take a seat. What brings you into the clinic today?',
        aiSpeechTr: 'Günaydın! Lütfen oturun. Bugün sizi kliniğe getiren şikayetiniz nedir?',
        expectedUserResponse: 'Good morning, doctor. I have had a terrible headache and a sore throat since yesterday.',
        userHint: 'Good morning doctor, I have a headache and sore throat (Başım ve boğazım ağrıyor) diyerek başla.',
        keywords: ['good', 'morning', 'doctor', 'headache', 'sore', 'throat', 'pain', 'yesterday'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Ateş & Semptom Detayları',
        aiSpeech: 'I am sorry to hear that. Have you had any fever or chills alongside the throat pain?',
        aiSpeechTr: 'Bunu duyduğuma üzüldüm. Boğaz ağrısının yanında ateş veya titreme hissettiniz mi?',
        expectedUserResponse: 'Yes, I felt feverish last night and my temperature was around 38 degrees.',
        userHint: 'Yes, I had a mild fever last night (Evet dün gece ateşim vardı) diyerek yanıtla.',
        keywords: ['yes', 'fever', 'temperature', 'chills', 'degrees', 'felt', 'night'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Boğaz ve Ciğer Muayenesi',
        aiSpeech: 'Let me take a quick look. Please open your mouth wide and say "Ah" for me.',
        aiSpeechTr: 'Hemen hızlıca bir bakayım. Lütfen ağzınızı iyice açın ve benim için "Aa" deyin.',
        expectedUserResponse: 'Ah... Does the back of my throat look very inflamed or red?',
        userHint: 'Ah... diyerek "Does it look inflamed?" (İltihaplı görünüyor mu?) diye sor.',
        keywords: ['ah', 'throat', 'inflamed', 'red', 'look', 'doctor', 'does'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Teşhis Açıklaması',
        aiSpeech: 'Your throat is slightly inflamed, but your lungs sound completely clear. It looks like a mild viral infection.',
        aiSpeechTr: 'Boğazınız biraz iltihaplı ama ciğerlerinizin sesi tamamen temiz geliyor. Hafif bir viral enfeksiyon gibi görünüyor.',
        expectedUserResponse: 'That is a relief! Do I need to take any antibiotics for this?',
        userHint: 'That is a relief! (Bu bir rahatlama!) de ve antibiyotik gerekip gerekmediğini sor.',
        keywords: ['relief', 'antibiotics', 'need', 'take', 'that', 'good', 'thank'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Reçete & İlaç Bilgisi',
        aiSpeech: 'No antibiotics needed. I will write a prescription for pain relief and a soothing throat spray.',
        aiSpeechTr: 'Antibiyotiğe gerek yok. Ağrıyı dindirmek için bir ağrı kesici ve rahatlatıcı bir boğaz spreyi reçete edeceğim.',
        expectedUserResponse: 'How often should I use the throat spray throughout the day?',
        userHint: 'How often should I use the throat spray? (Boğaz spreyini günde kaç kez kullanmalıyım?) diye sor.',
        keywords: ['often', 'how', 'use', 'spray', 'throat', 'day', 'prescription'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Tavsiyeler & Reçeteyi Teslim Etme',
        aiSpeech: 'Use it three times a day after meals, drink plenty of warm fluids, and get lots of rest!',
        aiSpeechTr: 'Yemeklerden sonra günde üç kez kullanın, bol ılık sıvı tüketin ve bol bol dinlenin!',
        expectedUserResponse: 'Thank you so much for your care, Dr. Emma. Have a wonderful day!',
        userHint: 'Thank you so much for your care, Dr. Emma! (İlginiz için teşekkürler!) diyerek vedalaş.',
        keywords: ['thank', 'much', 'care', 'doctor', 'emma', 'day', 'goodbye'],
      },
    ],
  },
  {
    id: 'job-interview',
    title: 'Job Interview & Professional Introduction',
    titleTr: 'İş Mülakatı & Profesyonel Kariyer Tanıtımı',
    category: 'interview',
    level: 'B1',
    durationMin: 8,
    icon: '💼',
    emoji: '🎯',
    badge: '3D Animasyon • Yeni',
    coverImage: 'scenarios/job-interview/interview.jpeg',
    description: "Londra'da prestijli bir şirkette İK Direktörü Sarah ile iş mülakatına katıl, tecrübelerini anlat, güçlü yönlerini ve kariyer hedeflerini paylaş, mülakatı başarıyla tamamla.",
    role: 'İş Adayı (Job Candidate)',
    aiRole: 'Kıdemli İK Yöneticisi & Mülakatçı',
    aiName: 'Sarah',
    situation: "Sarah seni Londra Canary Wharf'taki modern cam ofisinde güler yüzle karşılar, CV'ni inceler ve seni daha yakından tanımak için samimi ve profesyonel sorular sorar.",
    objectives: [
      {
        id: 'obj_1',
        text: 'Introduce your professional background and current field clearly.',
        textTr: 'Mesleki geçmişinizi ve uzmanlık alanınızı net şekilde tanıtın.',
        hint: 'Kalıp: "I have a background in technology and project coordination."',
      },
      {
        id: 'obj_2',
        text: 'Explain why you applied for this role and your key strengths.',
        textTr: 'Bu pozisyona neden başvurduğunuzu ve güçlü yönlerinizi açıklayın.',
        hint: 'Kalıp: "My greatest strength is problem-solving and adapting quickly."',
      },
      {
        id: 'obj_3',
        text: 'Ask an insightful question about team collaboration.',
        textTr: 'Ekip içi iş birliği ve çalışma kültürü hakkında bir soru sorun.',
        hint: 'Kalıp: "Could you tell me more about how the team collaborates on projects?"',
      },
    ],
    starterAiMessage: 'Good morning! Thank you for coming in today. To get started, could you tell me a little bit about yourself?',
    suggestedVocab: [
      { term: 'Background', tr: 'Mesleki geçmiş / Özgeçmiş', phonetic: '/ˈbæk.ɡraʊnd/' },
      { term: 'Strength', tr: 'Güçlü yön / Yetenek', phonetic: '/streŋθ/' },
      { term: 'Deadline', tr: 'Son teslim tarihi', phonetic: '/ˈded.laɪn/' },
      { term: 'Collaborate', tr: 'İş birliği yapmak', phonetic: '/kəˈlæb.ə.reɪt/' },
      { term: 'Opportunity', tr: 'Fırsat / Olanak', phonetic: '/ˌɒp.əˈtjuː.nə.ti/' },
      { term: 'Adaptable', tr: 'Uyum sağlayabilen', phonetic: '/əˈdæp.tə.bəl/' },
    ],
    keyPhrases: [
      { en: 'I have a background in technology and digital projects.', tr: 'Teknoloji ve dijital projeler alanında bir geçmişim var.' },
      { en: 'My greatest strength is problem-solving under tight deadlines.', tr: 'En büyük gücüm dar teslim tarihlerinde problem çözebilmektir.' },
      { en: 'I admire your company culture and high-impact international vision.', tr: 'Şirket kültürünüzü ve yüksek etkili uluslararası vizyonunuzu takdir ediyorum.' },
      { en: 'Could you tell me more about how the team collaborates?', tr: 'Ekibin nasıl iş birliği yaptığı hakkında biraz daha bilgi verebilir misiniz?' },
    ],
    videoPath: 'scenarios/job-interview',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Karşılama & Kendini Tanıtma',
        aiSpeech: 'Good morning! Thank you for coming in today. To get started, could you tell me a little bit about yourself?',
        aiSpeechTr: 'Günaydın! Bugün geldiğiniz için teşekkürler. Başlamak adına, bize biraz kendinizden bahsedebilir misiniz?',
        expectedUserResponse: 'Good morning, Sarah! I have a background in technology and I love collaborating with innovative teams.',
        userHint: 'Good morning Sarah, I have a background in... diyerek mesleki geçmişini özetle.',
        keywords: ['good', 'morning', 'sarah', 'background', 'technology', 'experience', 'love', 'teams'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Başvuru Nedeni & Motivasyon',
        aiSpeech: 'That is great experience! What made you interested in joining our company for this role?',
        aiSpeechTr: 'Harika bir deneyim! Bu pozisyon için şirketimize katılma konusunda ilginizi çeken ne oldu?',
        expectedUserResponse: 'I admire your innovative culture, and I want to contribute to high-impact international projects.',
        userHint: 'I admire your company culture... (Şirket kültürünüzü takdir ediyorum) kalıbını kullan.',
        keywords: ['admire', 'culture', 'innovative', 'contribute', 'international', 'projects', 'company', 'role'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'En Güçlü Yönün',
        aiSpeech: 'We value that passion! What would you consider your greatest professional strength?',
        aiSpeechTr: 'Bu tutkuya çok değer veriyoruz! En büyük mesleki güçlü yönünüzün ne olduğunu söylerdiniz?',
        expectedUserResponse: 'My greatest strength is problem-solving and adapting quickly to new challenges.',
        userHint: 'My greatest strength is problem-solving (En büyük gücüm problem çözmektir) kalıbıyla yanıtla.',
        keywords: ['greatest', 'strength', 'problem-solving', 'adapting', 'quickly', 'challenges', 'learning'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Baskı ve Zaman Yönetimi',
        aiSpeech: 'That is essential here. How do you usually handle tight deadlines or stressful situations?',
        aiSpeechTr: 'Burada bu çok önemli. Genellikle sıkışık teslim tarihlerini veya stresli durumları nasıl yönetirsiniz?',
        expectedUserResponse: 'I prioritize tasks, communicate transparently with the team, and stay focused on solutions.',
        userHint: 'I prioritize tasks and communicate with the team (Görevleri önceliklendirir ve ekiple iletişim kurarım) de.',
        keywords: ['prioritize', 'tasks', 'communicate', 'team', 'focused', 'solutions', 'stay', 'deadlines'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Takım Çalışması & İletişim',
        aiSpeech: 'We value teamwork here. How do you like to collaborate with your team?',
        aiSpeechTr: 'Burada takım çalışmasına çok değer veriyoruz. Ekibinizle nasıl iş birliği yapmayı seversiniz?',
        expectedUserResponse: 'I believe in open communication, active listening, and supporting my teammates.',
        userHint: 'I believe in open communication (Açık iletişime ve ekip desteğine inanırım) diyerek yanıtla.',
        keywords: ['team', 'communication', 'collaborate', 'support', 'listen', 'together', 'open', 'work'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Adayın Sorusu & Kapanış',
        aiSpeech: 'You have given wonderful answers! Before we wrap up, do you have any questions for me about the team?',
        aiSpeechTr: 'Harika yanıtlar verdiniz! Bitirmeden önce, ekip hakkında bana sormak istediğiniz bir soru var mı?',
        expectedUserResponse: 'Yes, could you tell me more about how the team collaborates on day-to-day projects?',
        userHint: 'Could you tell me more about the team? (Ekip hakkında biraz daha bilgi verebilir misiniz?) diye sor.',
        keywords: ['could', 'tell', 'more', 'team', 'collaborates', 'projects', 'thank', 'sarah'],
      },
    ],
  },
  {
    id: 'fitness-gym',
    title: 'Gym Workout & Personal Training',
    titleTr: 'Spor Salonunda Antrenman & Fitness Koçu',
    category: 'daily',
    level: 'A2',
    durationMin: 7,
    icon: '🏋️‍♂️',
    emoji: '💪',
    badge: '3D Animasyon • Yeni',
    coverImage: 'scenarios/fitness-gym/gym.jpeg',
    description: "Modern spor salonunda motive edici antrenör Coach Leo ile buluş, fitness hedeflerini belirle, ısınma ve ağırlık hareketlerini doğru formla uygula, enerjik bir antrenman yap.",
    role: 'Spor Salonu Üyesi',
    aiRole: 'Kişisel Fitness Antrenörü',
    aiName: 'Coach Leo',
    situation: "Coach Leo seni modern, aydınlık ve enerjik bir spor salonunda karşılar; hedeflerini sorar, ısınma ve omuz egzersizlerinde sana rehberlik eder.",
    objectives: [
      {
        id: 'obj_1',
        text: 'State your fitness goals (building strength and stamina).',
        textTr: 'Fitness hedeflerinizi (güç kazanmak ve kondisyon) belirtin.',
        hint: 'Kalıp: "I want to build strength and improve my stamina."',
      },
      {
        id: 'obj_2',
        text: 'Ask about weights and warm-up duration.',
        textTr: 'Isınma süresini ve dambıl ağırlığını sorun.',
        hint: 'Kalıp: "Should I start with three or five kilograms?"',
      },
      {
        id: 'obj_3',
        text: 'Confirm proper lifting form and thank your coach.',
        textTr: 'Doğru kaldırma formunu teyit edin ve antrenörünüze teşekkür edin.',
        hint: 'Kalıp: "Thank you so much, Coach Leo! See you next workout!"',
      },
    ],
    starterAiMessage: 'Hey there! Welcome to the gym! What are your fitness goals for today?',
    suggestedVocab: [
      { term: 'Stamina', tr: 'Kondisyon / Dayanıklılık', phonetic: '/ˈstæm.ɪ.nə/' },
      { term: 'Treadmill', tr: 'Koşu bandı', phonetic: '/ˈtred.mɪl/' },
      { term: 'Dumbbell', tr: 'Dambıl / El ağırlığı', phonetic: '/ˈdʌm.bel/' },
      { term: 'Hydrated', tr: 'Yeterli su tüketmiş', phonetic: '/ˈhaɪ.dreɪ.tɪd/' },
      { term: 'Posture', tr: 'Duruş / Vücut formu', phonetic: '/ˈpɒs.tʃər/' },
      { term: 'Workout', tr: 'Antrenman / İdman', phonetic: '/ˈwɜːk.aʊt/' },
    ],
    keyPhrases: [
      { en: 'I want to build strength and improve my stamina.', tr: 'Güç kazanmak ve kondisyonumu geliştirmek istiyorum.' },
      { en: 'How many minutes should I warm up on the treadmill?', tr: 'Koşu bandında kaç dakika ısınmalıyım?' },
      { en: 'Should I start with three or five kilograms?', tr: 'Üç kilo ile mi beş kilo ile mi başlayayım?' },
      { en: 'Thank you so much, Coach Leo! See you next workout!', tr: 'Çok teşekkürler Koç Leo! Bir sonraki idmanda görüşürüz!' },
    ],
    videoPath: 'scenarios/fitness-gym',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Karşılama & Fitness Hedefleri',
        aiSpeech: 'Hey there! Welcome to the gym! What are your fitness goals for today?',
        aiSpeechTr: 'Hey merhaba! Salona hoş geldin! Bugünkü fitness hedeflerin neler?',
        expectedUserResponse: 'Hello Coach Leo! I want to build strength and improve my stamina.',
        userHint: 'Hello Coach Leo! I want to build strength (Güç kazanmak istiyorum) diyerek başla.',
        keywords: ['hello', 'coach', 'leo', 'strength', 'stamina', 'fitness', 'goals', 'build'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Isınma & Koşu Bandı',
        aiSpeech: 'Awesome! Let us start with a light warm-up on the treadmill.',
        aiSpeechTr: 'Harika! Koşu bandında hafif bir ısınmayla başlayalım.',
        expectedUserResponse: 'Sounds good! How many minutes should I warm up for?',
        userHint: 'Sounds good! How many minutes? (Kulağa iyi geliyor, kaç dakika?) diye sor.',
        keywords: ['sounds', 'good', 'how', 'many', 'minutes', 'warm', 'up', 'treadmill'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Ağırlık Seçimi & Dambıllar',
        aiSpeech: 'Just five minutes! Then we will grab some light dumbbells for shoulders.',
        aiSpeechTr: 'Sadece beş dakika! Sonra omuzlar için hafif dambıllar alacağız.',
        expectedUserResponse: 'Got it! Should I start with three or five kilograms?',
        userHint: 'Should I start with three kilograms? (Üç kilo ile mi başlayayım?) diye sor.',
        keywords: ['got', 'start', 'three', 'five', 'kilograms', 'dumbbells', 'shoulders', 'weight'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Doğru Form & Nefes Kontrolü',
        aiSpeech: 'Start with three! Keep your back straight and breathe out as you lift.',
        aiSpeechTr: 'Üç ile başla! Sırtını dik tut ve ağırlığı kaldırırken nefes ver.',
        expectedUserResponse: 'Like this? I can feel the burn in my shoulders already!',
        userHint: 'Like this? I can feel the burn! (Böyle mi? Şimdiden hissediyorum!) de.',
        keywords: ['like', 'this', 'feel', 'burn', 'shoulders', 'already', 'form', 'straight'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Su Molası & Dinlenme',
        aiSpeech: 'Perfect form! Take a quick water break before our final set.',
        aiSpeechTr: 'Mükemmel form! Son setimizden önce hızlı bir su molası ver.',
        expectedUserResponse: 'Thanks coach! Staying hydrated really makes a huge difference.',
        userHint: 'Thanks coach! Staying hydrated helps (Teşekkürler koç, su içmek iyi geldi) de.',
        keywords: ['thanks', 'coach', 'water', 'hydrated', 'difference', 'break', 'drink'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Soğuma & Çak Bir Beşlik',
        aiSpeech: 'Great job today! Let us do some quick stretches and high five!',
        aiSpeechTr: 'Bugün harika bir iş çıkardın! Biraz esneyelim ve çak bir beşlik!',
        expectedUserResponse: 'Thank you so much, Coach Leo! See you at the next workout!',
        userHint: 'Thank you Coach Leo! See you next workout (Teşekkürler, bir sonraki idmanda görüşürüz) de.',
        keywords: ['thank', 'you', 'coach', 'leo', 'workout', 'stretches', 'five', 'bye'],
      },
    ],
  },
  {
    id: 'clothing-boutique',
    title: 'Shopping at a London Fashion Boutique',
    titleTr: 'Londra Butiğinde Kıyafet Alışverişi',
    category: 'daily',
    level: 'A2',
    durationMin: 7,
    icon: '🛍️',
    emoji: '👗',
    badge: '3D Animasyon • Yeni',
    coverImage: 'scenarios/clothing-boutique/boutique.jpeg',
    description: "Londra Soho'da şık bir butikte moda danışmanı Mia ile tanış, ceket ve kazak modellerini incele, beden ve renk tercihi yap, deneme kabininde dene ve alışverişini tamamla.",
    role: 'Mağazaya Gelen Müşteri',
    aiRole: 'Moda Danışmanı & Butik Görevlisi',
    aiName: 'Mia',
    situation: "Mia seni Londra Soho'daki modern şık butiğinde sıcak bir gülümsemeyle karşılar; aradığın kıyafetleri sorar, beden ve renk seçiminde rehberlik eder.",
    objectives: [
      {
        id: 'obj_1',
        text: 'State what clothing item and size you are looking for.',
        textTr: 'Hangi kıyafeti ve bedeni aradığınızı belirtin.',
        hint: 'Kalıp: "I am looking for a warm jacket, and I usually wear medium."',
      },
      {
        id: 'obj_2',
        text: 'Ask to try on the item in the fitting room.',
        textTr: 'Kıyafeti deneme kabininde denemek istediğinizi söyleyin.',
        hint: 'Kalıp: "Where are the fitting rooms? I will try it on right now."',
      },
      {
        id: 'obj_3',
        text: 'Inquire about the price and discounts before paying.',
        textTr: 'Ödeme yapmadan önce fiyatı ve indirim durumunu sorun.',
        hint: 'Kalıp: "How much is this jacket? That is a great deal!"',
      },
    ],
    starterAiMessage: 'Hello! Welcome to our boutique! Are you looking for anything special today?',
    suggestedVocab: [
      { term: 'Fitting room', tr: 'Deneme kabini', phonetic: '/ˈfɪt.ɪŋ ˌruːm/' },
      { term: 'Size', tr: 'Beden / Boyut', phonetic: '/saɪz/' },
      { term: 'Discount', tr: 'İndirim', phonetic: '/ˈdɪs.kaʊnt/' },
      { term: 'Receipt', tr: 'Fiş / Fatura', phonetic: '/rɪˈsiːt/' },
      { term: 'Comfortable', tr: 'Rahat / Konforlu', phonetic: '/ˈkʌm.fə.tə.bəl/' },
      { term: 'New arrival', tr: 'Yeni gelen ürün', phonetic: '/njuː əˈraɪ.vəl/' },
    ],
    keyPhrases: [
      { en: 'I am looking for a warm jacket or stylish sweater.', tr: 'Sıcak bir ceket veya şık bir kazak arıyorum.' },
      { en: 'I usually wear medium size, and I prefer navy blue.', tr: 'Genelde medium beden giyerim, laciverti tercih ederim.' },
      { en: 'It fits me perfectly and feels very comfortable!', tr: 'Üzerime tam oturdu ve çok rahat hissettiriyor!' },
      { en: 'That is a great deal! I will take it, thank you.', tr: 'Harika bir fırsat! Bunu alacağım, teşekkürler.' },
    ],
    videoPath: 'scenarios/clothing-boutique',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Karşılama & Ne Aradığını Sorma',
        aiSpeech: 'Hello! Welcome to our boutique! Are you looking for anything special today?',
        aiSpeechTr: 'Merhaba! Butiğimize hoş geldiniz! Bugün özel bir şey mi bakıyorsunuz?',
        expectedUserResponse: 'Hello! I am looking for a warm jacket or stylish sweater.',
        userHint: 'Hello! I am looking for a jacket (Bir ceket arıyorum) diyerek başla.',
        keywords: ['hello', 'looking', 'jacket', 'sweater', 'warm', 'stylish', 'clothes'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Beden & Renk Tercihi',
        aiSpeech: 'We have lovely new arrivals! What size and color do you prefer?',
        aiSpeechTr: 'Harika yeni gelenlerimiz var! Hangi beden ve rengi tercih edersiniz?',
        expectedUserResponse: 'I usually wear medium, and I really like navy blue or olive green.',
        userHint: 'I wear medium, and I like navy blue (Medium giyerim, lacivert severim) de.',
        keywords: ['medium', 'size', 'navy', 'blue', 'green', 'wear', 'color', 'prefer'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'Deneme Kabini',
        aiSpeech: 'This navy jacket would look stunning on you! The fitting rooms are right there.',
        aiSpeechTr: 'Bu lacivert ceket üzerinizde harika durur! Deneme kabinleri hemen şurada.',
        expectedUserResponse: 'Thank you! I will go try it on right now.',
        userHint: 'Thank you! I will try it on (Teşekkürler, hemen deneyeceğim) de.',
        keywords: ['thank', 'you', 'try', 'fitting', 'room', 'jacket', 'now'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Ayna Karşısında Fikir Alma',
        aiSpeech: 'That jacket looks amazing! It is one of our best designs.',
        aiSpeechTr: 'O ceket harika görünüyor! En iyi tasarımlarımızdan biridir.',
        expectedUserResponse: 'It feels very comfortable! How much is this jacket?',
        userHint: 'It feels comfortable! How much is it? (Çok rahat, fiyatı ne kadar?) diye sor.',
        keywords: ['feels', 'comfortable', 'how', 'much', 'jacket', 'price', 'amazing', 'looks'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Fiyat & İndirim',
        aiSpeech: 'The total price is fifty pounds with our special discount today!',
        aiSpeechTr: 'Bugünkü özel indirimimizle birlikte toplam fiyat 50 pound!',
        expectedUserResponse: 'That is a great deal! I will definitely take it, thank you.',
        userHint: 'That is a great deal! I will take it (Harika fırsat, kesinlikle alıyorum) de.',
        keywords: ['great', 'deal', 'take', 'it', 'definitely', 'thank', 'discount', 'price'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Ödeme & Fatura Teslimi',
        aiSpeech: 'Here is your bag and receipt! Enjoy wearing your new jacket, goodbye!',
        aiSpeechTr: 'İşte çantanız ve fişiniz! Yeni ceketinizi güzel günlerde giyin, hoşça kalın!',
        expectedUserResponse: 'Thank you so much for your help, Mia! Have a wonderful day!',
        userHint: 'Thank you for your help, Mia! (Yardımın için teşekkürler Mia!) diyerek vedalaş.',
        keywords: ['thank', 'you', 'help', 'mia', 'wonderful', 'day', 'goodbye', 'receipt'],
      },
    ],
  },
  {
    id: 'istanbul-tour',
    title: 'Istanbul City Highlights & Cultural Journey',
    titleTr: 'Büyülü İstanbul Şehir Turu & Kültür Yolculuğu',
    category: 'travel',
    level: 'A2',
    durationMin: 10,
    icon: '🕌',
    emoji: '🇹🇷',
    badge: '3D Animasyon • Özel 8 Adım',
    coverImage: 'scenarios/istanbul-tour/istanbul.jpeg',
    description: "Boğaz'ın serin rüzgarından Galata'nın tarihi taş sokaklarına, İstiklal Caddesi'nin kırmızı nostaljik tramvayından Kapalıçarşı'nın baharat kokularına ve sevimli sokak kedilerine kadar 8 adımda büyülü İstanbul'u İngilizce keşfet.",
    role: 'İstanbul Seyyahı',
    aiRole: 'İstanbul Rehberi & Hikaye Anlatıcısı',
    aiName: 'Ela',
    situation: "Ela seni Boğaz kıyısında güler yüzle karşılar; Galata, İstiklal, Kapalıçarşı, Ortaköy, Sultanahmet ve Kadıköy Moda duraklarında İstanbul'un ruhunu ve sevimli sokak kedilerini İngilizce anlatır.",
    objectives: [
      {
        id: 'obj_1',
        text: 'Describe the Bosphorus, seagulls, and historic ferry views.',
        textTr: 'Boğaz manzarasını, martıları ve tarihi vapurları tarif edin.',
        hint: 'Kalıp: "The view of the Bosphorus and seagulls is incredible!"',
      },
      {
        id: 'obj_2',
        text: 'Talk about Istanbul street cats and historic neighborhoods.',
        textTr: 'İstanbul sokak kedilerinden ve tarihi semtlerden bahsedin.',
        hint: 'Kalıp: "Istanbul cats are so adorable and friendly!"',
      },
      {
        id: 'obj_3',
        text: 'Order Turkish tea by the sea and share your impressions.',
        textTr: 'Deniz kenarında Türk çayı sipariş edip izlenimlerinizi paylaşın.',
        hint: 'Kalıp: "Turkish tea in this tulip glass with the bridge view is wonderful!"',
      },
    ],
    starterAiMessage: 'Welcome to Istanbul! The view of the Bosphorus is breathtaking today!',
    suggestedVocab: [
      { term: 'Bosphorus', tr: 'İstanbul Boğazı', phonetic: '/ˈbɒs.fər.əs/' },
      { term: 'Seagull', tr: 'Martı', phonetic: '/ˈsiː.ɡʌl/' },
      { term: 'Ferry', tr: 'Vapur / Feribot', phonetic: '/ˈfer.i/' },
      { term: 'Cobblestone', tr: 'Arnavut kaldırımı / Taş sokak', phonetic: '/ˈkɒb.əl.stəʊn/' },
      { term: 'Bazaar', tr: 'Çarşı / Pazar', phonetic: '/bəˈzɑːr/' },
      { term: 'Tulip glass', tr: 'İnce belli çay bardağı', phonetic: '/ˈtʃuː.lɪp ɡlɑːs/' },
      { term: 'Historic', tr: 'Tarihi / Tarihsel', phonetic: '/hɪˈstɒr.ɪk/' },
      { term: 'Breathtaking', tr: 'Nefes kesici', phonetic: '/ˈbreθˌteɪ.kɪŋ/' },
    ],
    keyPhrases: [
      { en: 'The view of the Bosphorus and seagulls is breathtaking.', tr: 'Boğaz ve martıların manzarası nefes kesici.' },
      { en: 'Istanbul cats are so adorable and well cared for.', tr: 'İstanbul kedileri çok sevimli ve çok iyi bakılıyor.' },
      { en: 'Turkish tea in a traditional tulip glass is wonderful.', tr: 'Geleneksel ince belli bardakta Türk çayı harika.' },
      { en: 'Standing between these ancient historic monuments feels majestic.', tr: 'Bu kadim tarihi anıtların arasında durmak muhteşem hissettiriyor.' },
    ],
    videoPath: 'scenarios/istanbul-tour',
    videoReady: true,
    videoSteps: [
      {
        step: 1,
        videoFile: 'step_1.mp4',
        title: 'Boğaz & Vapur Manzarası',
        aiSpeech: 'Welcome to Istanbul! The view of the Bosphorus is breathtaking today!',
        aiSpeechTr: 'İstanbul\'a hoş geldin! Bugün Boğaz manzarası nefes kesici!',
        expectedUserResponse: 'It is incredible! The seagulls and historic ferries look like a painting.',
        userHint: 'It is incredible! (İnanılmaz!) diyerek Boğaz manzarasına hayranlığını belirt.',
        keywords: ['incredible', 'seagulls', 'ferries', 'bosphorus', 'painting', 'view', 'istanbul'],
      },
      {
        step: 2,
        videoFile: 'step_2.mp4',
        title: 'Galata Kulesi & Sokak Kedisi',
        aiSpeech: 'Look at this friendly street cat resting near the historic Galata Tower!',
        aiSpeechTr: 'Tarihi Galata Kulesi\'nin yanında dinlenen şu cana yakın sokak kedisine bak!',
        expectedUserResponse: 'Istanbul cats are so adorable! Everyone treats them with so much love.',
        userHint: 'Istanbul cats are adorable! (İstanbul kedileri çok sevimli!) de.',
        keywords: ['cats', 'adorable', 'love', 'galata', 'tower', 'treats', 'friendly'],
      },
      {
        step: 3,
        videoFile: 'step_3.mp4',
        title: 'İstiklal Caddesi & Kırmızı Tramvay',
        aiSpeech: 'Here is Istiklal Street! Hear the bell of the nostalgic red tram?',
        aiSpeechTr: 'İşte İstiklal Caddesi! Kırmızı nostaljik tramvayın çan sesini duyuyor musun?',
        expectedUserResponse: 'Yes, it is so energetic! I love the historic architecture of these buildings.',
        userHint: 'Yes, it is so energetic! (Evet, çok enerjik!) diyerek caddenin atmosferini öv.',
        keywords: ['energetic', 'tram', 'architecture', 'buildings', 'historic', 'istiklal', 'street'],
      },
      {
        step: 4,
        videoFile: 'step_4.mp4',
        title: 'Kapalıçarşı & Mozaik Lambalar',
        aiSpeech: 'Welcome inside the Grand Bazaar! The colorful handmade lamps look magical!',
        aiSpeechTr: 'Kapalıçarşı\'ya hoş geldin! Renkli el yapımı lambalar büyüleyici görünüyor!',
        expectedUserResponse: 'The aromas of spices and sparkling lanterns are absolutely fascinating!',
        userHint: 'The aromas of spices are fascinating! (Baharat kokuları büyüleyici!) de.',
        keywords: ['aromas', 'spices', 'lanterns', 'fascinating', 'grand', 'bazaar', 'lamps', 'magical'],
      },
      {
        step: 5,
        videoFile: 'step_5.mp4',
        title: 'Ortaköy & Boğaz Çay Molası',
        aiSpeech: 'Time for a tea break! Fresh Turkish tea by the sea is perfect.',
        aiSpeechTr: 'Çay molası vakti! Deniz kenarında taze demli Türk çayı harika gider.',
        expectedUserResponse: 'Turkish tea in this tulip glass with the bridge view is wonderful!',
        userHint: 'Turkish tea with the bridge view is wonderful! (Köprü manzaralı çay harika!) de.',
        keywords: ['turkish', 'tea', 'tulip', 'glass', 'bridge', 'wonderful', 'view', 'sea'],
      },
      {
        step: 6,
        videoFile: 'step_6.mp4',
        title: 'Tarihi Sultanahmet Meydanı',
        aiSpeech: 'We are at Sultanahmet! Centuries of history meet right here in this square.',
        aiSpeechTr: 'Sultanahmet\'teyiz! Yüzyılların tarihi tam burada, bu meydanda buluşuyor.',
        expectedUserResponse: 'Standing between these ancient historic monuments feels so majestic!',
        userHint: 'Standing between historic monuments feels majestic! (Tarihin ortasında durmak muhteşem!) de.',
        keywords: ['standing', 'ancient', 'historic', 'monuments', 'majestic', 'sultanahmet', 'square'],
      },
      {
        step: 7,
        videoFile: 'step_7.mp4',
        title: 'Kadıköy Moda Sahili & Gün Batımı',
        aiSpeech: 'We crossed to the Asian side! The sunset over Moda is breathtaking.',
        aiSpeechTr: 'Anadolu yakasına geçtik! Moda üzerindeki gün batımı nefes kesici.',
        expectedUserResponse: 'The golden sunset over the sea is unforgettable. Kadikoy has such a cool vibe.',
        userHint: 'The sunset over the sea is unforgettable! (Denizdeki gün batımı unutulmaz!) de.',
        keywords: ['golden', 'sunset', 'sea', 'unforgettable', 'kadikoy', 'moda', 'vibe', 'asian'],
      },
      {
        step: 8,
        videoFile: 'step_8.mp4',
        title: 'Gece Boğaz Köprüsü Işıkları & Veda',
        aiSpeech: 'What a memorable journey! Istanbul will always hold a piece of your heart!',
        aiSpeechTr: 'Ne unutulmaz bir yolculuktu! İstanbul her zaman kalbinde bir yer tutacak!',
        expectedUserResponse: 'Thank you so much, Ela! This city tour was truly unforgettable, goodbye!',
        userHint: 'Thank you so much, Ela! (Çok teşekkürler Ela!) diyerek vedalaş.',
        keywords: ['thank', 'you', 'ela', 'city', 'tour', 'unforgettable', 'goodbye', 'istanbul'],
      },
    ],
  },
  {
    id: 'job-interview-tech',
    title: 'Senior Developer Tech Interview',
    titleTr: 'Kıdemli Yazılımcı İş Mülakatı',
    category: 'interview',
    level: 'B2',
    durationMin: 15,
    icon: '💼',
    emoji: '👨‍💻',
    badge: 'Popüler • Kariyer',
    description: 'Yurtdışı merkezli bir teknoloji şirketinde teknik lider ile mimari kararlar, sistem tasarımı ve geçmiş tecrübelerin üzerine derin bir mülakat simülasyonu.',
    role: 'Aday Yazılım Mühendisi',
    aiRole: 'Teknik Mülakatçı (VP of Engineering)',
    aiName: 'Alex Thorne',
    situation: 'Alex seni selamlar ve geçmişteki büyük ölçekli bir projenin teknik mimarisini, karşılaştığın darboğazları nasıl çözdüğünü anlatmanı ister.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Introduce your engineering background and recent tech stack concisely.',
        textTr: 'Yazılım geçmişini ve son kullandığın teknolojileri kısaca tanıt.',
        hint: 'Kalıp: "I have over X years of experience primarily working with..."',
      },
      {
        id: 'obj_2',
        text: 'Explain a tough technical challenge and how you solved it.',
        textTr: 'Karşılaştığın zorlu bir teknik problemi ve çözüm yöntemini açıkla.',
        hint: 'STAR Tekniği: Situation, Task, Action, Result sırasını kullan.',
      },
      {
        id: 'obj_3',
        text: 'Ask a thoughtful question about the company’s engineering culture.',
        textTr: 'Şirketin mühendislik kültürü ve CI/CD süreçleri hakkında soru sor.',
        hint: 'Kalıp: "Could you tell me more about how your team approaches code review and deployment cycles?"',
      },
    ],
    starterAiMessage: "Hello! Thank you for taking the time to join today's interview. I've gone through your resume and was quite intrigued by your background. To kick things off, could you briefly walk me through a recent complex system you designed or optimized?",
    suggestedVocab: [
      { term: 'Scalability', tr: 'Ölçeklenebilirlik', phonetic: '/ˌskeɪ.ləˈbɪl.ə.ti/' },
      { term: 'Bottleneck', tr: 'Darboğaz / Tıkanıklık', phonetic: '/ˈbɒt.əl.nek/' },
      { term: 'Trade-off', tr: 'Ödünleşim / Karar dengesi', phonetic: '/ˈtreɪd.ɒf/' },
      { term: 'Throughput', tr: 'İşlem hacmi / Debi', phonetic: '/ˈθruː.pʊt/' },
      { term: 'Asynchronous', tr: 'Eşzamansız', phonetic: '/eɪˈsɪŋ.krə.nəs/' },
    ],
    keyPhrases: [
      { en: 'We decided to decouple the services to improve fault tolerance.', tr: 'Hata toleransını artırmak için servisleri birbirinden ayırmaya karar verdik.' },
      { en: 'The main bottleneck was database connection pooling under peak traffic.', tr: 'En büyük darboğaz zirve trafikte veritabanı bağlantı havuzuydu.' },
      { en: 'In retrospect, choosing an event-driven architecture saved considerable latency.', tr: 'Geriye dönüp baktığımızda, olaya dayalı mimari seçmek gecikmeyi ciddi oranda azalttı.' },
    ],
  },
  {
    id: 'b2b-product-pitch',
    title: 'Enterprise B2B Product Demo & Pitch',
    titleTr: 'Kurumsal B2B Ürün Sunumu & Satış',
    category: 'business',
    level: 'B2',
    durationMin: 12,
    icon: '📊',
    emoji: '🚀',
    badge: 'İş Dünyası',
    description: 'Büyük bir kurumsal müşterinin Satın Alma Direktörüne SaaS ürününüzün ROI (Yatırım Getirisi) değerini anlatın ve itirazları yönetin.',
    role: 'Ürün Satış Direktörü',
    aiRole: 'Kurumsal Müşteri (Chief Information Officer)',
    aiName: 'Eleanor Vance',
    situation: 'Eleanor mevcut sistemlerinin pahalı olduğunu biliyor ancak yeni bir geçişin getireceği risklerden endişeli.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Highlight the core value proposition and efficiency gains of your platform.',
        textTr: 'Platformunuzun temel değer önerisini ve verimlilik kazanımlarını vurgulayın.',
        hint: 'Kalıp: "Our solution seamlessly integrates with your stack, reducing operational overhead by 30%."',
      },
      {
        id: 'obj_2',
        text: 'Address the budget and onboarding timeframe concerns confidently.',
        textTr: 'Bütçe ve adaptasyon süresi çekincelerini güven vererek yanıtlayın.',
        hint: 'Kalıp: "We provide a dedicated onboarding specialist and guarantee zero downtime migration."',
      },
      {
        id: 'obj_3',
        text: 'Propose a 14-day proof of concept (PoC) pilot.',
        textTr: '14 günlük pilot deneme (PoC) teklif ederek anlaşmayı bağlayın.',
        hint: 'Kalıp: "How about we initiate a 2-week pilot with your core team so you can validate the metrics yourself?"',
      },
    ],
    starterAiMessage: "Good morning! Thanks for the meeting. We're currently evaluating several vendors to overhaul our internal communication workflows. What makes your platform distinct from what we currently have in place?",
    suggestedVocab: [
      { term: 'Seamless', tr: 'Kusursuz / Kesintisiz', phonetic: '/ˈsiːm.ləs/' },
      { term: 'Return on Investment', tr: 'Yatırım Getirisi (ROI)', phonetic: '/rɪˈtɜːn ɒn ɪnˈvest.mənt/' },
      { term: 'Implementation', tr: 'Uygulama / Kurulum', phonetic: '/ˌɪm.plɪ.menˈteɪ.ʃən/' },
      { term: 'Overhead', tr: 'Genel gider / Ek yük', phonetic: '/ˈəʊ.və.hed/' },
    ],
    keyPhrases: [
      { en: 'Our clients typically see a 40% reduction in customer turnaround time.', tr: 'Müşterilerimiz genellikle yanıt sürelerinde %40 düşüş görüyor.' },
      { en: 'Security compliance is built directly into our core infrastructure.', tr: 'Güvenlik uyumluluğu doğrudan ana altyapımıza entegre edilmiştir.' },
    ],
  },
  {
    id: 'airport-transit-trouble',
    title: 'Missed Connection Flight at Heathrow',
    titleTr: 'Havalimanında Aktarma Uçuşunu Kaçırma',
    category: 'travel',
    level: 'A2',
    durationMin: 10,
    icon: '✈️',
    emoji: '🧳',
    badge: 'Seyahat • Pratik',
    description: 'İlk uçuşunuz rötar yaptığı için Londra Heathrow havalimanında aktarmalı uçuşunuzu kaçırdınız. Havayolu görevlisi ile görüşüp yeni bilet ve otel talep edin.',
    role: 'Mağdur Yolcu',
    aiRole: 'Havayolu Müşteri Hizmetleri Temsilcisi',
    aiName: 'David Miller',
    situation: 'David hava muhalefeti sebebiyle yoğun bir kuyruğu yönetmeye çalışıyor. Kibar ama kararlı bir şekilde haklarınızı talep etmelisiniz.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Explain that your incoming flight was delayed by 2 hours.',
        textTr: 'Gelen uçuşunuzun 2 saat geciktiğini ve aktarmayı kaçırdığınızı anlatın.',
        hint: 'Kalıp: "My previous flight was delayed, which caused me to miss my connection to New York."',
      },
      {
        id: 'obj_2',
        text: 'Request to be booked on the next available direct flight.',
        textTr: 'Mümkün olan en yakın direkt uçuşa yeniden rezervasyon yapılmasını isteyin.',
        hint: 'Kalıp: "Could you please rebook me onto the next available flight today?"',
      },
      {
        id: 'obj_3',
        text: 'Ask for a hotel voucher or meal allowance if the flight is tomorrow.',
        textTr: 'Uçuş yarına kalırsa otel ve yemek kuponu talep edin.',
        hint: 'Kalıp: "Since the flight is tomorrow morning, does the airline provide complimentary accommodation?"',
      },
    ],
    starterAiMessage: "Next in line, please! Good afternoon. How can I help you today?",
    suggestedVocab: [
      { term: 'Delayed', tr: 'Rötarlı / Gecikmiş', phonetic: '/dɪˈleɪd/' },
      { term: 'Connection', tr: 'Aktarma uçuşu', phonetic: '/kəˈnek.ʃən/' },
      { term: 'Accommodation', tr: 'Konaklama', phonetic: '/əˌkɒm.əˈdeɪ.ʃən/' },
      { term: 'Voucher', tr: 'Kupon / Fiş', phonetic: '/ˈvaʊ.tʃər/' },
    ],
    keyPhrases: [
      { en: 'Here is my boarding pass and baggage tag number.', tr: 'İşte biniş kartım ve bagaj fiş numaram.' },
      { en: 'Is there any direct flight departing later this evening?', tr: 'Bu akşam daha geç kalkan herhangi bir direkt uçuş var mı?' },
    ],
  },
  {
    id: 'coffee-shop-smalltalk',
    title: 'Artisan Cafe Barista & Small Talk',
    titleTr: 'Kahve Siparişi & Doğal Sohbet',
    category: 'daily',
    level: 'A1',
    durationMin: 8,
    icon: '☕',
    emoji: '🥐',
    badge: 'Günlük Yaşam',
    description: 'Londra Soho’da popüler bir kahvecide özel bir kahve siparişi verin, süt ve şurup tercihi yapın ve barista ile sıcak bir sohbet gerçekleştirin.',
    role: 'Müşteri',
    aiRole: 'Samimi Barista',
    aiName: 'Chloe',
    situation: 'Chloe sana günün nasıl geçtiğini sorar ve favori kahve çekirdeklerini önerir.',
    objectives: [
      {
        id: 'obj_1',
        text: 'Order a customized coffee drink with specific milk and size.',
        textTr: 'Özel süt ve boyut tercihini belirterek kahve siparişi ver.',
        hint: 'Kalıp: "Could I have a medium oat flat white with extra shot, please?"',
      },
      {
        id: 'obj_2',
        text: 'Ask about a bakery item in the glass display.',
        textTr: 'Vitrindeki taze kruvasan veya kek hakkında soru sor.',
        hint: 'Kalıp: "Are the almond croissants freshly baked this morning?"',
      },
      {
        id: 'obj_3',
        text: 'Pay via contactless card and exchange polite pleasantries.',
        textTr: 'Temassız kartla ödeme yap ve iyi günler dile.',
        hint: 'Kalıp: "I will pay with card contactless. Have a wonderful rest of your day!"',
      },
    ],
    starterAiMessage: "Hey there! Welcome to Bean & Brew. How's your morning going so far? What can I get started for you today?",
    suggestedVocab: [
      { term: 'Oat milk', tr: 'Yulaf sütü', phonetic: '/əʊt mɪlk/' },
      { term: 'Decaf', tr: 'Kafeinsiz kahve', phonetic: '/ˈdiː.kæf/' },
      { term: 'Pastry', tr: 'Hamur işi / Çörek', phonetic: '/ˈpeɪ.stri/' },
      { term: 'Contactless', tr: 'Temassız (ödeme)', phonetic: '/ˈkɒn.tækt.ləs/' },
    ],
    keyPhrases: [
      { en: 'Could I get that to go, please?', tr: 'Onu paket (al-götür) olarak alabilir miyim?' },
      { en: 'Keep the change, thanks!', tr: 'Üstü kalsın, teşekkürler!' },
    ],
  },
  {
    id: 'visa-embassy-interview',
    title: 'US Embassy Visa Officer Interview',
    titleTr: 'ABD Konsolosluğu Vize Mülakatı',
    category: 'interview',
    level: 'B1',
    durationMin: 12,
    icon: '🏛️',
    emoji: '🛂',
    badge: 'Kritik • Resmi',
    description: 'ABD B1/B2 turist ve iş vizesi için konsolosluk memuru ile mülakat. Ziyaret amacınızı, seyahat planınızı ve ülkenize bağlılığınızı kanıtlayın.',
    role: 'Vize Başvuru Sahibi',
    aiRole: 'Konsolosluk Vize Memuru (Consular Officer)',
    aiName: 'Officer Bradley',
    situation: 'Bradley ciddi, resmi ve sorulara net, doğrudan ve kendinden emin yanıtlar bekleyen bir memurdur.',
    objectives: [
      {
        id: 'obj_1',
        text: 'State the exact primary purpose and planned duration of your trip.',
        textTr: 'Seyahatinizin kesin amacını ve kalış sürenizi net olarak ifade edin.',
        hint: 'Kalıp: "I am traveling to attend the annual TechCon conference in San Francisco for 8 days."',
      },
      {
        id: 'obj_2',
        text: 'Explain your current job, employer, and economic ties to your home country.',
        textTr: 'Mevcut işinizi, çalıştığınız şirketi ve ülkenizdeki bağlarınızı açıklayın.',
        hint: 'Kalıp: "I work as a Lead Engineer at XYZ for 3 years, and I will resume my duties immediately after the trip."',
      },
      {
        id: 'obj_3',
        text: 'Clarify who is covering the flight and hotel expenses.',
        textTr: 'Uçak ve konaklama masraflarının kim tarafından karşılanacağını belirtin.',
        hint: 'Kalıp: "My employer is fully sponsoring the travel and accommodation costs."',
      },
    ],
    starterAiMessage: "Good morning. Please place your documents in the tray. State clearly the primary purpose of your travel to the United States.",
    suggestedVocab: [
      { term: 'Sponsor', tr: 'Maddi sponsor / Masrafları karşılayan', phonetic: '/ˈspɒn.sər/' },
      { term: 'Itinerary', tr: 'Seyahat planı / Gezi rotası', phonetic: '/aɪˈtɪn.ər.ər.i/' },
      { term: 'Employment', tr: 'İstihdam / Çalışma durumu', phonetic: '/ɪmˈplɔɪ.mənt/' },
      { term: 'Return ticket', tr: 'Dönüş bileti', phonetic: '/rɪˈtɜːn ˈtɪk.ɪt/' },
    ],
    keyPhrases: [
      { en: 'Here is my official conference invitation letter.', tr: 'İşte resmi konferans davet mektubum.' },
      { en: 'I have strong family and professional ties in my home country.', tr: 'Kendi ülkemde güçlü ailevi ve mesleki bağlarım var.' },
    ],
  },
];
